name: trivy-offline-to-quay.io
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
jobs:
  build:
    env:    
      image_name: trivy-offline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          path: .
          registry: ${{ secrets.REGISTRY_SERVER }}
          repository: ${{ secrets.REGISTRY_NAMESPACE }}/${{ env.image_name }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: "latest"
